contentColumnType: string
fieldGroup: 97fa4163-0da8-47b1-a9ec-e6f4382ff078
handle: awards
instructions: 'Enter medals received'
name: Awards
searchable: true
settings:
  contentTable: '{{%matrixcontent_awards}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
