contentColumnType: 'decimal(12,2)'
fieldGroup: 97fa4163-0da8-47b1-a9ec-e6f4382ff078
handle: price
instructions: ''
name: Price
searchable: false
settings:
  decimals: '2'
  defaultValue: '0'
  max: null
  min: '0'
  prefix: ''
  previewCurrency: AUD
  previewFormat: currency
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
