enableVersioning: true
handle: winesList
name: 'Wines List'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f3400d6f-0f33-4cef-9521-f8f6620399ec:
    enabledByDefault: true
    hasUrls: true
    template: _private/wines-list
    uriFormat: our-wines
type: single
